### ISSUE TITLE
onUploadProgress never called on android (real device)

### ISSUE THREAD

**Issue by vvusts** [infinitered/apisauce#117]
Is there something special that need to be done to make this work on (react-native) android?
Ios work fine.
```
const api = create({baseURL:...
...
api.post(url, arguments, { onUploadProgress: value => {
            // on android this is never reached      
        }}).then((res) => {
```

**Comment by skellock** [comment]
Hmm.. not that I'm aware of.  It's not firing for you eh?  

I'm on vacation at the moment, but I will check when i get home.

**Comment by vvusts** [comment]
Ok thank you.
I replaced it with another library for now.
It's react 43.1 and android phone.
IOS works fine.

**Comment by vvusts** [comment]
Are there any updates on this?

**Comment by skellock** [comment]
Going to close this since it's a few months old, but ya, no news here. 

This feature passes directly into axios.  You might want to check on their issue tracker to see if it's come up.  I know I've used this fine on iOS.  

Might want to try it again with an updated React Native.  They fix stuff like this all the time.

Thanks for the issue. I'll keep an eye out for this the next time I use it on Android and report back if there's any success or failure.
