### ISSUE TITLE
[Bug] Base URL is not validated when changing in instance

### ISSUE THREAD

**Issue by Ranmus** [infinitered/apisauce#140]
This emits error:
```
const api = create({baseURL: ''})
```
And this not:
```
const api = create({baseURL: '/'})
api.setBaseURL('')
```
I also suggest to allow setting empty base url and force browser to get current protocol and domain.

**Comment by robinheinze** [comment]
Hey @Ranmus! Thanks for the issue. We're deferring all calls to axios, so any inconsistency would be an issue on their side. It's possible it's fixed on their end and we just need to update the version of axios, since I know we're a few versions behind. PRs are very much welcome if you decide to look into that :)
