### ISSUE TITLE
UNKNOW_ERROR always return when running in jest

### ISSUE THREAD

**Issue by tatiesmars** [infinitered/apisauce#144]
I am trying to run some sort of integration test of our react native app as we are able now to run locally all our backend. (why not test the app directly against the backend, right?). It seem that apisauce is not working at all with Jest or am I doing something wrong? 

* How we trigger an http request toward a service
```js
  requestSmsToken(phoneNumber: string): Promise<RequestSmsTokenResponse> {
    return this.api // this.api is an apisauce instance setup with a baseUrl 
      .post('request-sms-token', {
        number: phoneNumber,
      })
      .then((response) => {
        // parse error
       return response.data;
      });
  }
```

* Simplified apisauce test that return `UNKNOW_ERROR`
```js
  describe('requestSmsToken', () => {
    test('happy case 1 - request token', () => {
      let phone = generatePhoneNumber()
      const core = new Core(CORE_URL) // return our Api class containing the `requestSmsToken` method
      return expect(core.requestSmsToken(phone))
        .resolves.toMatchObject({})
    })
```

* apisauce response
```js
    { duration: 16,
      problem: 'UNKNOWN_ERROR',
      ok: false,
      status: null,
      headers: null,
      config:
       { adapter: [Function: httpAdapter],
         transformRequest: { '0': [Function: transformRequest] },
         transformResponse: { '0': [Function: transformResponse] },
         timeout: 5000,
         xsrfCookieName: 'XSRF-TOKEN',
         xsrfHeaderName: 'X-XSRF-TOKEN',
         maxContentLength: -1,
         validateStatus: [Function: validateStatus],
         headers:
          { Accept: 'application/json',
            'Content-Type': 'application/json',
            'User-Agent': 'axios/0.16.2',
            'Content-Length': 27,
            host: 'localhost:1234' },
         baseURL: 'http://localhost:1234/',
         method: 'post',
         url: 'http://localhost:1234/request-sms-token',
         data: '{"number":"+8613058198192"}' },
      data: null }
```

I m confuse by this error. Is it due to jest env? or is it an apisauce related issue? 
version
```json
{
    "jest": "^22.2.1",
    "apisauce": "^0.14.3",
}

**Comment by skellock** [comment]
You probably don't want to be running api calls in your tests.  I wonder if `jest` is removing anything that it relies on?

**Comment by tatiesmars** [comment]
We already have some unit test wrote but having integration test will give more confident of the code base. So you guess the problem is link to jest removing some dependencies apisauce rely on?

**Comment by skellock** [comment]
I'm speculating.  Which is my specialty.  😆 

Even for integration tests, I'd still [mock this](https://github.com/infinitered/apisauce/issues/50#issuecomment-305764519), though.  When you cross a boundary like APIs and hit a server, you might (will) be introducing external state inadvertently.  

You can run yourself into trouble as:

- a failing test could impact the rest of your tests
- running in parallel is a nightmare
- the configuration required for CI to run your test becomes a nightmare or just not possible
- extra time is required to reset the server after every test

I promise I'm not trying to talk you out of this because I can't properly answer your real problem here.  🤣 

If you're using `react-native`, using Jest is a completely different runtime environment.  You're not really using `jsc` on mobile anymore.  You're using `node`. Since the environment is different, `jest` has to do a bunch of polyfilling and slight of hand to make this work.

Also, `axios` has two different [XHR libs internally](https://github.com/axios/axios/blob/14057dc0bd9811a9fda773588f66de9f4aa0f617/package.json#L70) (depending on environment), and this may be contributing.
