### ISSUE TITLE
[Question] iOS / Android support with React Native

### ISSUE THREAD

**Issue by RossKinsella** [infinitered/apisauce#146]
Hi there,

I'm considering brining this library in for my next RN project. In my last project I had some headaches around parsing responses and handling failure states which this library seems to offer a better solution for. One thing which concerns me however is the TODO at the bottom of your readme.

https://github.com/infinitered/apisauce#todo
> TODO: Detect network failures on iOS and Android.

Offline functionality is something which I will be supporting in this project so I'm curious as to what the current behaviour is when network problems are at play? My use case is an app which will be running and making requests for users on a car journey, so I'm expecting periodic drops in connection

**Comment by skellock** [comment]
When you make a response on a device with no network, the request should come back with this:

```
{
  ok: false,
  problem: 'NETWORK_ERROR'
}
```

Unfortunately, due to JavaScriptCore on older Android devices (and iOS < 8.3), that's not always the case.  It returns `CONNECTION_ERROR`.

The React Native network stack is... uh.... complicated.  There's like 5 middlemen and this is a 6th.

I've been using `apisauce` happily on React Native for a few years now.  Much of it's magic comes from `axios`.  It simply adds some niceties (read: opinions) around that.

I think between `apisauce` and `NetInfo`, you should be able to detect most scenarios though.
