### ISSUE TITLE
Creating the api at runtime

### ISSUE THREAD

**Issue by MaxToyberman** [infinitered/apisauce#149]
I am using Ignite boilerplate fore react-native, my sagas/index.js looks like that

```
import { takeLatest } from 'redux-saga/effects'
import { ConfigTypes } from '../redux/ConfigurationRedux'
import { getConfig } from './ConfigSagas'
import Api from '../services/Api'

const api = Api.create()

export default function * root () {
    yield [
        takeLatest(ConfigTypes.GET_CONFIG_REQUEST, getConfig, api),
        
    ]
}
```

The problem is that, I don't have a base url at the beginning, my config arrives from my server, and when it arrives I want to init the api object.

it needs to be initialised inside the `getConfig` function.

What is the best way to do this  (setBaseURL is not good because I can't set an empty baseurl) 

Thank You

**Comment by skellock** [comment]
Hi Max,

Could your api start off with any URL? as long as it knows it shouldn't be called for certain requests.  

Then when the right one arrives, you change the api via `setBaseURL`? I know you said explicitly it wouldn't work, but I'm not sure how it couldn't as long as you're setting it to something valid.

Another option would be pass an `apiManager`.  That's just an object that will manage the process of setting the API to the right one.  This would be the thing you pass to your saga functions.

It would force you to change the interface in all your sagas a bit... but i don't know how to do it otherwise.  (well, I do, but I'm not going to recommend to you that your `const api` become a `let api`).

=)

So I'm not sure about "best" way, but there's several ways.  There's probably something clever you can do with `setContext` and `getContext` too.  Those are new saga apis I've never tried though.

**Comment by MaxToyberman** [comment]
Hi @skellock ,
setBaseURL actually works, but i a required not to start off with any url. (but with an empty baseURL)
but it is not possible in apisauce
