### ISSUE TITLE
Support for SSL Pinning

### ISSUE THREAD

**Issue by alvintd92** [infinitered/apisauce#241]
Firstly, thank you so much for the awesome library.

Just wondering if in your roadmap, will there be support for SSL pinning?

**Comment by jamonholmgren** [comment]
Hi @alvintd92! Glad you're enjoying using apisauce!

Sorry about the delay on this. I haven't been paying attention to apisauce issues for ... a while, I guess. :-)

I'm not super familiar with SSL pinning, but from doing some searches, it looks like there are a few options.

1. You can add [TrustKit](https://github.com/datatheorem/TrustKit) to the native side and (I think?) axios will use that
2. You can try out [https://www.npmjs.com/package/react-native-ssl-pinning](https://www.npmjs.com/package/react-native-ssl-pinning), which might handle this for you

Since apisauce is intended to be a thin wrapper around Axios, your best bet is to do some googling around "axios ssl pinning react native".

If you found another solution, feel free to share!
