### ISSUE TITLE
Why was 2.x a breaking release?

### ISSUE THREAD

**Issue by mattcollier** [infinitered/apisauce#257]
Happy New Year all!  I'm trying to assess the impacts of updating to apisauce@2.  I see the release notes state that updating the axios dep from 0.19.x to 0.20.x is a breaking change without any further description.  https://github.com/infinitered/apisauce/releases/tag/v2.0.0, the PR https://github.com/infinitered/apisauce/pull/250

I don't see any mention of breaking changes in the axios changelog: https://github.com/axios/axios/blob/master/CHANGELOG.md 

Can anyone highlight what the breaking changes are for apisauce@2?

**Comment by jamonholmgren** [comment]
@mattcollier We decided to make it a breaking change because it was an axios breaking change and we upgraded axios. However, it seems like a really tiny breaking change, so the risk is low.

https://github.com/infinitered/apisauce/pull/250/files

Primarily: https://github.com/axios/axios/releases/tag/v0.20.0-0
